### ISSUE TITLE
Fail to preview in Android Studio 2.2 preview 3

### ISSUE THREAD

**Issue by Piasy** [mmin18/FlexLayout#10]
Android Studio 2.2 has introduced the New UI Designer & Constraint Layout, but in the preview tab of AS, it can't preview my layout, the stack trace is:

``` java
java.lang.NoSuchFieldError: FlexLayout_Layout
    at com.github.mmin18.widget.FlexLayout$LayoutParams.<init>(FlexLayout.java:104)
    at com.github.mmin18.widget.FlexLayout.generateLayoutParams(FlexLayout.java:353)
    at com.github.mmin18.widget.FlexLayout.generateLayoutParams(FlexLayout.java:36)
    at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:860)
    at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
    at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:317)
    at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
    at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:962)
    at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
    at com.android.tools.idea.rendering.RenderTask.lambda$inflate$58(RenderTask.java:659)
    at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:380)
    at com.android.tools.idea.rendering.RenderTask.inflate(RenderTask.java:659)
    at com.android.tools.idea.uibuilder.model.NlModel.inflate(NlModel.java:327)
    at com.android.tools.idea.uibuilder.model.NlModel.render(NlModel.java:384)
    at com.android.tools.idea.uibuilder.editor.NlPreviewForm$Pending.<init>(NlPreviewForm.java:234)
    at com.android.tools.idea.uibuilder.editor.NlPreviewForm.setFile(NlPreviewForm.java:293)
    at com.android.tools.idea.uibuilder.editor.NlPreviewManager$3.run(NlPreviewManager.java:290)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
    at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:267)
    at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2440)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:279)
    at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
    at com.intellij.util.Alarm$Request.run(Alarm.java:398)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Piasy** [comment]
Well, after I press the `build` button, it's previewed successfully.
