### ISSUE TITLE
Setting views relative to another view

### ISSUE THREAD

**Issue by chiragpurohit71085** [mmin18/FlexLayout#4]
Hi

When I am trying to set views relatively to each other I a getting following error. I have taken care of defining references view first.

I am using Android studio 2.0. I am facing this issue in my demo app as well as sample app along with this library.

(Reference a specific view using view's id)

java.lang.IllegalArgumentException: unknown identifier view2, layout_top=view2.bottom+20dp
    at com.github.mmin18.widget.FlexLayout$TokenReader.parseStr(FlexLayout.java:1334)
    at com.github.mmin18.widget.FlexLayout$TokenReader.readToken(FlexLayout.java:1286)
    at com.github.mmin18.widget.FlexLayout$RPN.parse(FlexLayout.java:1420)
    at com.github.mmin18.widget.FlexLayout$LayoutParams.<init>(FlexLayout.java:78)
    at com.github.mmin18.widget.FlexLayout.generateLayoutParams(FlexLayout.java:325)
    at com.github.mmin18.widget.FlexLayout.generateLayoutParams(FlexLayout.java:32)
    at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:837)
    at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
    at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:229)
    at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:426)
    at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:510)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:498)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:967)
    at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:498)
    at com.android.tools.idea.rendering.RenderTask.access$600(RenderTask.java:72)
    at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:610)
    at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:607)
    at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:359)
    at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:607)
    at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:629)
    at com.intellij.android.designer.designSurface.AndroidDesignerEditorPanel$7.run(AndroidDesignerEditorPanel.java:519)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
    at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:271)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:286)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:244)
    at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)

Here is my sample XML file...

<?xml version="1.0" encoding="utf-8"?>
<com.github.mmin18.widget.FlexLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

```
<Button
    app:layout_width="(152/3.84)%"
    app:layout_height="(64/5.70)%"
    android:text="New Button"
    android:id="@+id/button"
    app:layout_centerX="50%"

    app:layout_top="(73.68%)"/>

<ImageView

    app:layout_width="(116/3.84)%"
    app:layout_height="(94/5.70)%"
    app:layout_top="(25/5.70)%"
    app:layout_left="0dp"
    android:id="@+id/imageView2"
    android:background="@color/abc_search_url_text_pressed"/>

<TextView
    android:id="@+id/view2"
    app:layout_width="(244/3.84)%"
    app:layout_height="(32/5.70)%"
    android:text="New Text1"
    app:layout_left="(122/3.84)%"
    app:layout_top="(32/5.70)%"/>


<TextView
    android:id="@+id/textView3"
    android:layout_width="244dp"
    android:layout_height="32dp"
    android:text="New Text"
    app:layout_centerX="view2.centerX"
    app:layout_top="view2.bottom+20dp"

    />
```

</com.github.mmin18.widget.FlexLayout>

Let me know if I am missing anything.

**Comment by mmin18** [comment]
It works fine on my side. Can you checkout the branch https://github.com/mmin18/FlexLayout/tree/tmp/test_chiragpurohit71085 and see if it works on your phone?

I've changed gradle build tool to 2.0.0, and I'm also using AndroidStudio 2.0

![device-2016-04-13-223528](https://cloud.githubusercontent.com/assets/748883/14497134/5c355f9e-01c8-11e6-908a-92a4130d9416.png)

**Comment by chiragpurohit71085** [comment]
Hi

Thanks. I"ll check and keep you updated on this.

Regards

**Comment by chiragpurohit71085** [comment]
Hi

Sorry to bother you again.. But I am facing the same issue.

Here is the sequence.
-  I have imported your project from given branch and opened layout
  _sample04_reference_other_views.xml._
  *- *At this point there were no errors (but layout was not reflecting xml
  code, all elements are overlapped on left side)
- I have cleaned project and rebuild the project.(I start getting rendering
  issue)
- Manually deleted build folder from android project (& clean & rebuild),
  but getting the same issue.

Let me know if I am missing  anything.

java.lang.IllegalArgumentException: unknown identifier view1,
layout_top=view1.bottom
at
com.github.mmin18.widget.FlexLayout$TokenReader.parseStr(FlexLayout.java:1334)
at
com.github.mmin18.widget.FlexLayout$TokenReader.readToken(FlexLayout.java:1298)
at com.github.mmin18.widget.FlexLayout$RPN.parse(FlexLayout.java:1420)
at
com.github.mmin18.widget.FlexLayout$LayoutParams.<init>(FlexLayout.java:78)
at
com.github.mmin18.widget.FlexLayout.generateLayoutParams(FlexLayout.java:325)
at
com.github.mmin18.widget.FlexLayout.generateLayoutParams(FlexLayout.java:32)
at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:837)
at
android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
at
com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:229)
at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:426)
at
com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
at
com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:510)
at
com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:498)
at
com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:967)
at
com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:498)
at
com.android.tools.idea.rendering.RenderTask.access$600(RenderTask.java:72)
at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:610)
at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:607)
at
com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:359)
at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:607)
at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:629)
at
com.intellij.android.designer.designSurface.AndroidDesignerEditorPanel$7.run(AndroidDesignerEditorPanel.java:519)
at
com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
at
com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
at
com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:271)
at
com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:286)
at
com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:244)
at
com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
at
com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at
java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
at java.lang.Thread.run(Thread.java:695)

**Comment by mmin18** [comment]
Can you send me the apk file under yout FlexLayout/sample/build/output/apk/sample-debug.apk?

**Comment by chiragpurohit71085** [comment]
Hi

Thanks for your quick responses.

I think there is some confusion here. 

If I run application it works perfect. I am getting issue in layout file (XML only). So if I create my view using % layout it shows perfectly in xml file (Design view), but when I use relative to another view, I am getting given error and can not visualize my view.

(I am from ios background and among all libraries or hacks I found, this is the best one. Even with % layout I am able to get started. Thank you very much for this.)

Regards,

**Comment by mmin18** [comment]
Oh you mean the preview in AndroidStudio. Sorry I misunderstood.

I can't guarantee but I'll try to make it work in preview in later versions. Thanks for your suggestion.

**Comment by chiragpurohit71085** [comment]
Hi

Thanks...Waiting for your update.

Regards

**Comment by mmin18** [comment]
Fixed in v1.2.2. Check the update.

**Comment by chiragpurohit71085** [comment]
Hi

Thanks.I"ll check this and update you ASAP.

Thanks again

**Comment by chiragpurohit71085** [comment]
Hi

I have checked and its working fine. Thank you very much.

Regards,
